spring.application.name=api-gateway

server.port=9191

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

# route ID
# route URI
# route predicate

# course-service
spring.cloud.gateway.server.webmvc.routes[0].id=course-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://course-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/courses/**

# student-service
spring.cloud.gateway.server.webmvc.routes[1].id=student-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://student-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/students/**

# college-service
spring.cloud.gateway.server.webmvc.routes[2].id=college-service-route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://college-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/colleges/**